// CITIES
export const GET_CITIES_REQUEST = "GET_CITIES_REQUEST"
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS"
export const GET_CITIES_FAIL = "GET_CITIES_FAIL"

// COUNTRIES
export const GET_COUNTRIES_REQUEST = "GET_COUNTRIES_REQUEST"
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS"
export const GET_COUNTRIES_FAIL = "GET_COUNTRIES_FAIL"

// DIRECTIONS
export const GET_DIRECTIONS_REQUEST = "GET_DIRECTIONS_REQUEST"
export const GET_DIRECTIONS_SUCCESS = "GET_DIRECTIONS_SUCCESS"
export const GET_DIRECTIONS_FAIL = "GET_DIRECTIONS_FAIL"

// ESTATE_TYPES
export const GET_ESTATE_TYPES_REQUEST = "GET_ESTATE_TYPES_REQUEST"
export const GET_ESTATE_TYPES_SUCCESS = "GET_ESTATE_TYPES_SUCCESS"
export const GET_ESTATE_TYPES_FAIL = "GET_ESTATE_TYPES_FAIL"

// PROPERTY_TYPES
export const GET_PROPERTY_TYPES_REQUEST = "GET_PROPERTY_TYPES_REQUEST"
export const GET_PROPERTY_TYPES_SUCCESS = "GET_PROPERTY_TYPES_SUCCESS"
export const GET_PROPERTY_TYPES_FAIL = "GET_PROPERTY_TYPES_FAIL"
